name:                oracle
version:             0.1.0.0
github:              "dselsam/oracle"
license:             Apache-2.0
author:              "Daniel Selsam"
copyright:           "2020 Microsoft Corporation"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dselsam/oracle#README>

dependencies:
- base >= 4.7 && < 5
- hspec
- mtl
- containers
- vector
- pqueue

library:
  source-dirs: src

executables:
  oracle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oracle

tests:
  oracle-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oracle
