# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChoicePoint.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)


_sym_db = _symbol_database.Default()

import Embeddable_pb2 as Embeddable__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='ChoicePoint.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x43hoicePoint.proto\x1a\x10\x45mbeddable.proto\"J\n\x0b\x43hoicePoint\x12\x1d\n\x08snapshot\x18\x01 \x01(\x0b\x32\x0b.Embeddable\x12\x1c\n\x07\x63hoices\x18\x02 \x03(\x0b\x32\x0b.Embeddableb\x06proto3'
  ,
  dependencies=[Embeddable__pb2.DESCRIPTOR,])




_CHOICEPOINT = _descriptor.Descriptor(
  name='ChoicePoint',
  full_name='ChoicePoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot', full_name='ChoicePoint.snapshot', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='choices', full_name='ChoicePoint.choices', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=113,
)

_CHOICEPOINT.fields_by_name['snapshot'].message_type = Embeddable__pb2._EMBEDDABLE
_CHOICEPOINT.fields_by_name['choices'].message_type = Embeddable__pb2._EMBEDDABLE
DESCRIPTOR.message_types_by_name['ChoicePoint'] = _CHOICEPOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChoicePoint = _reflection.GeneratedProtocolMessageType('ChoicePoint', (_message.Message,), {
  'DESCRIPTOR' : _CHOICEPOINT,
  '__module__' : 'ChoicePoint_pb2'
  # @@protoc_insertion_point(class_scope:ChoicePoint)
  })
_sym_db.RegisterMessage(ChoicePoint)


# @@protoc_insertion_point(module_scope)
