# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataPoint.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from learning import ChoicePoint_pb2 as ChoicePoint__pb2
from learning import Label_pb2 as Label__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='DataPoint.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0f\x44\x61taPoint.proto\x1a\x11\x43hoicePoint.proto\x1a\x0bLabel.proto\"E\n\tDataPoint\x12!\n\x0b\x63hoicePoint\x18\x01 \x01(\x0b\x32\x0c.ChoicePoint\x12\x15\n\x05label\x18\x02 \x01(\x0b\x32\x06.Labelb\x06proto3'
    ,
    dependencies=[ChoicePoint__pb2.DESCRIPTOR, Label__pb2.DESCRIPTOR, ])

_DATAPOINT = _descriptor.Descriptor(
    name='DataPoint',
    full_name='DataPoint',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='choicePoint', full_name='DataPoint.choicePoint', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='label', full_name='DataPoint.label', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=51,
    serialized_end=120,
)

_DATAPOINT.fields_by_name['choicePoint'].message_type = ChoicePoint__pb2._CHOICEPOINT
_DATAPOINT.fields_by_name['label'].message_type = Label__pb2._LABEL
DESCRIPTOR.message_types_by_name['DataPoint'] = _DATAPOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataPoint = _reflection.GeneratedProtocolMessageType('DataPoint', (_message.Message,), {
    'DESCRIPTOR': _DATAPOINT,
    '__module__': 'DataPoint_pb2'
    # @@protoc_insertion_point(class_scope:DataPoint)
})
_sym_db.RegisterMessage(DataPoint)

# @@protoc_insertion_point(module_scope)
